### ISSUE TITLE
How to use it to profile  under apache + mod_perl

### ISSUE THREAD

**Issue by zxiong** [agentzh/perl-systemtap-toolkit#2]
How to use it to profile under apache + mod_perl, seems I can not find the perl process.

**Comment by agentzh** [comment]
@zxiong Just choose an apache worker process as the target. But you need to ensure that the perl interpreter is statically linked into the apache server and has debug symbols enabled in both.

**Comment by agentzh** [comment]
@zxiong Technically we could add support for dynamically linked perl interpreter libraries, but it requires some more tweaks in the tool itself. So I recommend static linking at the moment. If you have the tuits to add support for dynamic linking, please submit a pull request. Thanks!

**Comment by zxiong** [comment]
@agentzh  thx very much

**Comment by agentzh** [comment]
@zxiong For offline profiling, you'd better just configure one single apache worker such that your test traffic must go through that single worker you're watching. Well, just a tip :)
